version: 2

jobs:
    build:
        docker:
            - image: node:10.10.0-alpine
        steps:
            - checkout
            - run:
                name: Install All Node Dependencies
                command: npm ci 
            - run:
                name: Run Unit Test Coverage and Collect Coverage Reports
                command: npm run coverage
            - store_artifacts:
                path: coverage
